name: vibecheck-db-only

services:
  vbc-mysql:
    image: mysql
    restart: always
    volumes:
      - vibecheck_mysql:/var/lib/mysql-data
    container_name: vbc-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: O3hlB8hciNHmFiLfgDeK
      MYSQL_DATABASE: vibecheck

volumes:
  vibecheck_mysql:
